"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dub.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AnalyticsEventNamesTypedDict(TypedDict):
    event_name: str
    r"""The name of the conversion event (lead or sale)"""
    clicks: NotRequired[float]
    r"""The number of clicks from this event name"""
    leads: NotRequired[float]
    r"""The number of leads from this event name"""
    sales: NotRequired[float]
    r"""The number of sales from this event name"""
    sale_amount: NotRequired[float]
    r"""The total amount of sales from this event name, in cents"""


class AnalyticsEventNames(BaseModel):
    event_name: Annotated[str, pydantic.Field(alias="eventName")]
    r"""The name of the conversion event (lead or sale)"""

    clicks: Optional[float] = 0
    r"""The number of clicks from this event name"""

    leads: Optional[float] = 0
    r"""The number of leads from this event name"""

    sales: Optional[float] = 0
    r"""The number of sales from this event name"""

    sale_amount: Annotated[Optional[float], pydantic.Field(alias="saleAmount")] = 0
    r"""The total amount of sales from this event name, in cents"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["clicks", "leads", "sales", "saleAmount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AnalyticsEventNames.model_rebuild()
except NameError:
    pass
