"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

from __future__ import annotations
from dub.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class DiscountCodeSchemaTypedDict(TypedDict):
    id: str
    r"""The unique ID of the discount code."""
    code: str
    r"""The alphanumeric discount code that customers can apply at checkout."""
    discount_id: Nullable[str]
    r"""The ID of the discount this code belongs to."""
    partner_id: str
    r"""The ID of the partner this discount code is assigned to."""
    link_id: str
    r"""The ID of the partner's referral link this discount code is associated with."""
    disabled_at: NotRequired[Nullable[str]]
    r"""When this discount code was disabled, which happens when a partner is banned or deactivated. We don't delete the discount code to avoid another partner claiming a banned/deactivated code (abuse vector)."""


class DiscountCodeSchema(BaseModel):
    id: str
    r"""The unique ID of the discount code."""

    code: str
    r"""The alphanumeric discount code that customers can apply at checkout."""

    discount_id: Annotated[Nullable[str], pydantic.Field(alias="discountId")]
    r"""The ID of the discount this code belongs to."""

    partner_id: Annotated[str, pydantic.Field(alias="partnerId")]
    r"""The ID of the partner this discount code is assigned to."""

    link_id: Annotated[str, pydantic.Field(alias="linkId")]
    r"""The ID of the partner's referral link this discount code is associated with."""

    disabled_at: Annotated[
        OptionalNullable[str], pydantic.Field(alias="disabledAt")
    ] = UNSET
    r"""When this discount code was disabled, which happens when a partner is banned or deactivated. We don't delete the discount code to avoid another partner claiming a banned/deactivated code (abuse vector)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["disabledAt"])
        nullable_fields = set(["discountId", "disabledAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    DiscountCodeSchema.model_rebuild()
except NameError:
    pass
